ECL001: <0>は必須項目です。
ECL002: <0>は「<1>」文字以下で入力してください。（現在<2>文字）
ECL003: <0>は「<1>」文字以上で入力してください。（現在<2>文字）
ECL004: <0>は半角数字で入力してください。
ECL005: <0>は半角英字で入力してください。
ECL006: <0>は半角英数で入力してください。
ECL007: メールアドレスを正しく入力してください。
ECL008: <0>は全角で入力してください。
ECL009: <0>は全角カナで入力してください。
ECL010: <0>は日付を正しく入力してください。
ECL011: <0>は日時を正しく入力してください。
ICL012: 検索結果は0件です。
ECL013: <0>が取得できませんでした。
ICL014: 指定された条件に該当するデータが存在しません。入力内容を確認してください。
ICL015: CSV出力件数は<0>件です。
ECL016: 入力した情報のいずれかの情報が間違っています。確認してから再度試してください。
ECL017: <0>は「<1>」文字で入力してください。（現在<2>文字）
ECL018: ファイル形式が誤っています。<0>を選択してください。
ECL019: ファイルフォーマットが正しくありませんヘッダー情報を確認してください。
ECL020: ファイルのサイズ制限<0>を超えています。
ECL021: ファイルの生成に失敗しました。
ECL022: 該当ファイルが存在しません。
ECL023: <0>が重複しています
ECL024: アクセス権限がありません
ECL025: <0>では半角英字および以下の文字以外はご使用いただけません。(「#」、「$」、「%」、「(」、「)」、「*」、「+」、「-」、「.」、「/」、「:」、「;」、「?」、「@」、「[」、「]」、「_ 」、「{」、「}」、「~」)
ECL026: <0>は<1>以降の日時を選択してください。
ECL027: <0>は本日以降の年月日を選択してください。
ICL028: カートが空です。
ECL029: ログインIDをパスワードにすることは出来ません。
ECL030: 新しいパスワードが確認用パスワードと一致しません。
ECL031: 存在しない社員情報です。ログインID、生年月日、認証キーを再度ご確認ください。
ECL032: 既に登録済のメールアドレスです。
ICL033: 入力内容に該当するお客様情報が存在しません。入力内容を確認してください。
ECL034: 変更内容を入力してください。
ECL035: 現在のパスワードが正しくありません。入力内容を確認してください。
ECL036: パスワードが確認用パスワードと一致しません。
ECL037: ログインIDまたはパスワードが正しくありません。初めてご利用になる場合は新規登録ボタンからお進みください。
ICL038: 現在、新しいお知らせはございません。
ICL039: お気に入り登録した商品はここに表示されます。
ICL040: <0>のご注文可能数量を超えています。<br/>大変申し訳ございませんが、現在<0>の在庫数は<1>となっております。
ICL041: 現在選択されている年月にご注文履歴はありません。
ICL042: 商品情報が取得できませんでした。
ICL043: 既に利用者登録済みです。ログイン画面よりログインを行ってください。
ECL049: 入力された絵文字は登録できません。
ECL053: <0>〜<1>の範囲で入力してください。
ECL056: 入力したコードは商品マスタに存在しません。入力内容を確認してください。
ECL057: 入力したコードは既に登録されています。入力内容を確認してください。
ECL058: No User Found
EBT019: すでにメールアドレスは登録されています。
EBT086: すでに証明書番号は登録されています。
EBT096: 登録・更新・削除処理に成功しました。
# Input title side text
input_title_max_len: <0>文字以下で入力してください。

# Batch error message
batch_system_error: システムエラーが発生しました。
batch_normal_error: 処理は異常終了しました
batch_finish_success: 処理は正常終了しました

b010_exists_record: 対象データ：<0>件
b010_not_exists_record: 対象データなし

b020_not_exists_record_of_mst: <0>：本日分のデータが未連携
b020_not_exists_record_of_mst_in_email_content: <0>連携エラー内容：本日分のデータが未連携

maintenance_body: ただいまメンテナンス中です。<0>に開始します。

batch_send_push_notification_success: Batch push notification at <0> has been completed successfully.
batch_send_push_notification_number_sent: "Number of push notification sent: <0>"
batch_send_push_notification_error: An error occurred while running batch push notification at <0>.

deviceTokens: "deviceTokens: <0>"
