version: '3'
services:
    nhs-ihs-admin:
        container_name: nhs-ihs-admin
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                user: bw
                uid: 1000
        ports:
            - '${APP_PORT:-80}:80'
        restart: always
        volumes:
            - "/var/log/docker-log/:/var/www/html/storage/logs"
        networks:
            - nhs-ihs-admin-net

    nhs-ihs-admin-dev:
        container_name: nhs-ihs-admin-dev
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
            args:
                user: bw
                uid: 1000
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - "./:/var/www/html"
        networks:
            - nhs-ihs-admin-net
networks:
    nhs-ihs-admin-net:
        driver: bridge
